### ISSUE TITLE
Correct Syntax to Impose Multi Signatures Book (Codex)

### ISSUE THREAD

**Issue by xlance-github** [Singond/PDFriend#1]
Hello @Singond

After trying hundreds of mix and match commands / parameters, still could NOT find the correct syntax to impose a Multi Signatures Book (Codex) !

The best I could find is (I know something should come after "book" but what ??? )
`java -jar pdfriend.jar impose --book ▼ --output TEST.pdf Input.pdf`
or
`java -jar pdfriend.jar impose --book ▼ --sheets-per-signature ▼ --output TEST.pdf Input.pdf`

Would really really appreciate some Examples of how commands / parameters are put in the correct order.
(P.S. I've already examined the embedded Help)

Thank You for an outstanding piece of software.

**Comment by Singond** [comment]
Hello Xlance,

I admit the documentation is far from complete. It has been some time since I worked on this project and I hope to improve it in the future.

The `--book` option requires an argument which describes how the sheet (or stack of sheets) is folded before being trimmed to form the signature. The syntax of this argument is a sequence of the following commands, separated by commas with no spaces:
- `H`: fold the sheet horizontally, with the top half going to the back
- `H-`: fold the sheet horizontally, with the top half going to the front
- `V`: fold the sheet vertically, with the right half going to the back
- `V-`: fold the sheet vertically, with the right half going to the front
The commands are given in the order they are performed. In the above description, the lower left corner of the unfolded sheet is assumed to be held in a fixed position.

For example, the layout in [this image](https://en.wikipedia.org/wiki/Imposition#/media/File:8up_imposition.svg) assumes the following operations, starting with the front facing up:
1. fold vertically between 13 and 16, putting 16 to the back
2. fold horizontally between 4 and 5, putting 5 to the front (what appears on top is actually page 8)
3. fold vertically between 4 and 13, putting 13 to the front (page 16 appears on top)
This can be performed using the option `--book V,H-,V-`.

I may be wrong, writing this off the top of my head. I hope the command works for You.

**Comment by xlance-github** [comment]
@Singond 
Works perfectly 👍 Thank You
Hope at some point you would implement "Scale to Fill" function which is still pending ;-)
️
